apiVersion: v2
name: app-backend
description: YT Video Creator Backend Application
type: application
version: 1.0.0
appVersion: "1.0.0"

maintainers:
  - name: Infrastructure Team
    email: infra@ytvideocreator.com

keywords:
  - video
  - ai
  - content-creation

sources:
  - https://github.com/abhishek2k21/Story-Genius
